name: Build & Release Electron App

on:
  push:
    tags:
      - "v*.*.*"   # Example: v1.0.0 → trigger release
  workflow_dispatch:  # allows manual run

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Package Electron App
        run: npm run dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mytyping-${{ matrix.os }}
          path: dist/*
